[package]
name = "optimize"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "optimize"
path = "src/main.rs"

[dependencies]
optimize-core = { path = "../optimize-core" }
